 [[redirects]]
  from = "/articles"
  to = "https://us-central1-horizontal-cab-336803.cloudfunctions.net/articles"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/article"
  to = "https://us-central1-horizontal-cab-336803.cloudfunctions.net/article"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}